# Generated by Django 4.2.26 on 2025-11-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_searchfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestlist',
            options={'permissions': [('can_toggle_public', 'Can toggle public/private on interest lists')]},
        ),
    ]
